#!/usr/bin/env bash
# configure the load balancer, install haproxy
sudo apt update
sudo apt -y install haproxy

sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy 
sudo sed -i -e '$a\listen vansa-front\n\tbind *:80\n\tbalance roundrobin\n\tserver 121577-web-01 52.91.119.110:80 check\n\tserver 121577-web-02 52.91.151.232:80 check\n' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
